FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            expose: true
            groups: ['user_full']
        email:
            expose: true
            groups: ['user_full']
