<?php

namespace Sioblog\CoreBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\ORM\QueryBuilder;
use Sioblog\CoreBundle\Entity\EventRole;
use Sioblog\CoreBundle\Entity\CustomerStatus;
use Sioblog\CoreBundle\Entity\State;
use Sioblog\CoreBundle\Entity\TicketOrderStatus;
use Sioblog\CoreBundle\Entity\User;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

}
