security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_provider:
            id: platform.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)
            security: false

        doc:
            pattern: ^/doc
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_resetting_request:
            pattern: ^/v1/resetting/request
            anonymous: true

        oauth_resetting_reset:
            pattern: ^/v1/resetting/reset/([^\/]*)$
            anonymous: true

        api:
            pattern:    ^/
            security: false
            # fos_oauth:  true
            # stateless:  true

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        # - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
