sioblog_api_article:
    type: rest
    prefix: /v1
    resource: "Sioblog\\ApiBundle\\Controller\\ArticleController"
    name_prefix:  api_1_
    
sioblog_api_user:
    type: rest
    prefix: /v1
    resource: "Sioblog\\ApiBundle\\Controller\\UserController"
    name_prefix:  api_1_
